import { Dimensions } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

// Screen Dimensions
export const SIZES = {
  // Screen dimensions
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  
  // Common spacing
  PADDING_SMALL: 8,
  PADDING_MEDIUM: 16,
  PADDING_LARGE: 20,// Default padding for most components
  PADDING_EXTRA_LARGE: 24,
  
  MARGIN_SMALL: 8,
  MARGIN_MEDIUM: 16,
  MARGIN_LARGE: 20,
  MARGIN_EXTRA_LARGE: 24,
  
  // Border radius
  BORDER_RADIUS_SMALL: 4,
  BORDER_RADIUS_MEDIUM: 8,
  BORDER_RADIUS_LARGE: 12,
  BORDER_RADIUS_EXTRA_LARGE: 16,
  BORDER_RADIUS_ROUND: 20,
  
  // Font sizes
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_REGULAR: 16,
  FONT_SIZE_LARGE: 18,
  FONT_SIZE_EXTRA_LARGE: 20,
  FONT_SIZE_TITLE: 24,
  FONT_SIZE_HEADING: 28,
  FONT_SIZE_HERO: 32,
  
  // Icon sizes
  ICON_SMALL: 16,
  ICON_MEDIUM: 20,
  ICON_LARGE: 24,
  ICON_EXTRA_LARGE: 32,
  
  // Button heights
  BUTTON_HEIGHT_SMALL: 36,
  BUTTON_HEIGHT_MEDIUM: 44,
  BUTTON_HEIGHT_LARGE: 52,
  
  // Input heights
  INPUT_HEIGHT: 48,
  
  // Component specific sizes
  SLIDER_HEIGHT: SCREEN_HEIGHT * 0.5, // 50% of screen height
  PAGINATION_DOT_SIZE: 8,
  PAGINATION_DOT_ACTIVE_WIDTH: 20,
  
  // Line heights
  LINE_HEIGHT_SMALL: 16,
  LINE_HEIGHT_MEDIUM: 20,
  LINE_HEIGHT_LARGE: 24,
  LINE_HEIGHT_EXTRA_LARGE: 28,
  
  // Border widths
  BORDER_WIDTH_THIN: 1,
  BORDER_WIDTH_MEDIUM: 2,
  BORDER_WIDTH_THICK: 3,
  
  // Shadow properties
  SHADOW_ELEVATION_SMALL: 2,
  SHADOW_ELEVATION_MEDIUM: 4,
  SHADOW_ELEVATION_LARGE: 8,
  
  // Common percentages of screen
  PERCENT_10: SCREEN_WIDTH * 0.1,
  PERCENT_20: SCREEN_WIDTH * 0.2,
  PERCENT_30: SCREEN_WIDTH * 0.3,
  PERCENT_40: SCREEN_WIDTH * 0.4,
  PERCENT_50: SCREEN_WIDTH * 0.5,
  PERCENT_60: SCREEN_WIDTH * 0.6,
  PERCENT_70: SCREEN_WIDTH * 0.7,
  PERCENT_80: SCREEN_WIDTH * 0.8,
  PERCENT_90: SCREEN_WIDTH * 0.9,
  PERCENT_100: SCREEN_WIDTH,
  
  // Height percentages
  HEIGHT_10: SCREEN_HEIGHT * 0.1,
  HEIGHT_20: SCREEN_HEIGHT * 0.2,
  HEIGHT_30: SCREEN_HEIGHT * 0.3,
  HEIGHT_40: SCREEN_HEIGHT * 0.4,
  HEIGHT_50: SCREEN_HEIGHT * 0.5,
  HEIGHT_60: SCREEN_HEIGHT * 0.6,
  HEIGHT_70: SCREEN_HEIGHT * 0.7,
  HEIGHT_80: SCREEN_HEIGHT * 0.8,
  HEIGHT_90: SCREEN_HEIGHT * 0.9,
  HEIGHT_100: SCREEN_HEIGHT,

  // Image sizes
  IMAGE_SIZE_SMALL: 60,
};

export default SIZES;
