import { StyleSheet } from "react-native";
import { moderateScale, verticalScale } from "../utils/Metrices";
import { version } from "react";

export const trialOrdersStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 10,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#000',
  },
  headerRightSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  countdownBadge: {
    backgroundColor: '#EAFEF1',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  countdownText: {
    color: '#00C264',
    fontWeight: '600',
    fontSize: 12,
  },
  notificationButton: {
    borderRadius: 20,
    overflow: 'hidden',
  },
  notificationButtonGradient: {
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: 15,
    gap: 10,
    borderWidth: 1,
    borderRadius: 30,
    marginHorizontal: 20,
    padding:8,
  },
  tabButton: {
    flex: 1,
    // paddingVertical: 8,
    // paddingHorizontal: 20,
    height:verticalScale(34),
    borderRadius: 20,
    borderColor: '#ccc',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeTabButton: {
    backgroundColor: '#000',
  },
  tabText: {
    color: '#000',
    fontWeight: '500',
    fontSize: 12,
  },
  activeTabText: {
    color: '#fff',
  },
  scrollContainer: {
    paddingHorizontal: 20,
  },
  trialCard: {
    backgroundColor: '#F6F6F6',
    borderColor:"#DBDBDB",
    borderWidth: 1,
    borderRadius: 14,
    // padding: 16,
    marginBottom: 16,
    overflow: 'hidden',
  },
  newTrialLabel: {
    fontWeight: '600',
    fontSize: 16,
    marginBottom: 10,
    alignSelf: 'center',
  },
  trialTimeBox: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 16,
    // marginBottom: 10,
    borderBottomWidth: 1,
    borderColor: '#DBDBDB',
  },
  trialTimeText: {
    fontSize: 14,
    color: '#666',
    marginRight: 6,
  },
  timeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
  },
  distanceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // marginBottom: 10,
  //  borderWidth: 1,
   backgroundColor: '#fff',
  //  paddingHorizontal: 32,
  },
  distanceText: {
    fontSize: 14,
    color: '#666',
  },
  boldText: {
    fontWeight: '600',
    color: '#000',
  },
  orderDetailsBox: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 14,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  orderTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  companyName: {
    fontWeight: '600',
    fontSize: 16,
    color: '#000',
    marginBottom: 8,
  },
  orderId: {
    fontSize: 12,
    color: '#555',
  },
  addressText: {
    fontSize: 13,
    color: '#424245',
    marginBottom: 6,
  },
  timeAway: {
    fontSize: 12,
    color: '#999',
    marginLeft: 6,
  },
  timeAwayRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  storeButton: {
    borderRadius: 30,
    overflow: 'hidden',
    marginTop: 20,
  },
  storeButtonGradient: {
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  storeButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },
  swipeToStoreContainer: {
    borderRadius: 25,
    overflow: 'hidden',
    marginTop: 20,
    marginBottom: 20,
    position: 'relative',
  },
  swipeToStoreGradient: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    minHeight: 50,
  },
  storeButtonArea: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  swipeIndicator: {
    position: 'absolute',
    zIndex: 2,
    left: 8,
    backgroundColor: '#fff',
    width: 44,
    height: 34,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  swipeHintText: {
    color: '#bbb',
    fontSize: 11,
    marginTop: 1,
  },
  disabledButtonContainer: {
    borderRadius: 25,
    backgroundColor: '#F6F6F6',
    marginTop: 0,
    marginBottom: 20,
    position: 'relative',
  },
  disabledButtonContent: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    minHeight: 50,
  },
  disabledButtonText: {
    color: '#999',
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0.15,
  },
  swipeContainer: {
    backgroundColor: '#fff',
    borderRadius: 30,
    height: 60,
    marginTop: 16,
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  swipeText: {
    color: '#888',
    fontSize: 14,
    fontWeight: '500',
  },
  trialStartCountdown: {
    textAlign: 'center',
    color: '#777',
    marginTop: 10,
    fontSize: 13,
  },
  bottomButtonContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    paddingTop: 10,
    backgroundColor: '#fff',
  },
});